version: '3'

services:
  web-app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django-gateway
    ports:
      - "8000:8000"
    networks:
      - my-network
    volumes:
      - ./database:/app/database

  llm-ai:
    image: llm-api-ai-app:latest
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network: